version: 1.0

name: Stack to setup a Flutter app optionally deploy to Google Play store
description: Use this stack to setup an Android App and deploy to google play store
branding:
  icon: "thumbs-up"
  color: "blue"

inputs:
  - name: APP_NAME
    description: Fluttter app name
    required: true

  - name: FLUTTER_VERSION                              
    default: '2.0.5'
    description: Version of Flutter SDK to be used
    validvalues:
    - '2.0.5'
    - '1.22.x'
    - '1.20.2'

  - name: JAVA_VERSION                                 
    default: v12.0.15
    description: Version of java to be used for this stack
    validvalues:
    - v12.0.15
    - v12.0.10

  - name: RUBY_VERSION                                 
    default: '2.6'
    description: Version of Ruby to be used for this stack
    validvalues:
    - '2.6'
    - '2.7'

  - name: DEPLOY_TO_PLAY_STORE
    description: Do you want to setup this stack to deploy to play store?
    default: 'false'
    validvalues:
    - 'true'
    - 'false'

  - name: ANDROID_KEYSTORE_BASE64
    description: Base64 encoded Android Keystore for signing
    default: 'test'
    required: true
    is_secret: true

  - name: ANDROID_PACKAGE_NAME
    description: Android Package name
    default: 'test'
    required: true
    is_secret: true

  - name: GOOGLE_SERVICE_ACCOUNT_KEY
    description: Google Service Account Key
    default: 'test'
    required: true
    is_secret: true

configs:
  - repo-metadata:
      parameters:
        description: 'Flutter deployed to play store'
        secrets: 
          - name: GOOGLE_SERVICE_ACCOUNT_KEY
            value: ${{inputs.GOOGLE_SERVICE_ACCOUNT_KEY}}
          - name: ANDROID_PACKAGE_NAME
            value: ${{inputs.ANDROID_PACKAGE_NAME}}
          - name: ANDROID_KEYSTORE_BASE64
            value: ${{inputs.ANDROID_KEYSTORE_BASE64}}
        topics:
          - flutter
          - android

  - branches:
    - name: main

  - environments:
    - name: development

github-apps:
- slug: codecov

init:
  - uses: ".github/workflows/stack-init.yaml"
